### ISSUE TITLE
Public release roadmap

### ISSUE THREAD

**Issue by marekdedic** [skaut/skaut-google-drive-gallery#52]
Co potřebujeme udělat před vypuštěním do světa:

V tomto pořadí:

- [x] Vyřešit umístění nápovědy
- [x] Opravit odkaz na nápovědu v #31
- [x] Opravit odkaz na nápovědu nápovědu v `readme.txt`
- [x] Merge #37
- [x] Verze 2.0.0 (#37 je zpětně nekompatibilní), push na WP.org
- [x] V tu chvíli může někdo začít řešit #33 a #36, protože už bude vše finální. Byl bych rád, kdyby se na to kouknul někdo s větším citem pro design než mám já.
- [x] #56
- [x] Taky můžeme dodělat nápovědu pro finální feature set. (#17)
- [x] Udělat s finální grafikou screenshoty na WP.org (#49)
- [x] Public release

Nezávisle na tom v mezičase:
- [x] #38
- [x] #41
- [x] #59
- [x] #60
- [x] #61
- [x] #63
- [x] Testování
- [x] Bugfixy

**Comment by GenaBitu** [comment]
Asi je to připravené na prime-time. @kalich5 - co myslíš?

**Comment by kalich5** [comment]
Jako podle mě jo... ;-)
